## <span style="color: DeepPink; ">2.5.3 DataFrame(pandas)とndarray(NumPy)の関係</span>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
excel_path='dataChapter2/2_pandas.xlsx'
df_p1 = pd.read_excel(excel_path, sheet_name='p1',index_col=0)

In [2]:
print("行列数：\n",df_p1.shape,"\n")
print("サイズ：\n",df_p1.size,"\n")
print("インデックス：\n",df_p1.index,"\n")
print("カラム名：\n",df_p1.columns,"\n")
print("値：\n",df_p1.values,"\n")
print("絶対座標指定：\n",df_p1.iloc[0,1],"\n")
print("絶対座標指定：\n",df_p1.iloc[0:3,[0]],"\n")
print("ラベル指定：\n",df_p1.loc[:,"糖度"],"\n")
print("ラベル指定：\n",df_p1.loc["リンゴ1",:],"\n")

行列数：
 (6, 2) 

サイズ：
 12 

インデックス：
 Index(['リンゴ1', 'リンゴ2', 'リンゴ3', 'リンゴ4', 'リンゴ5', 'リンゴ6'], dtype='object') 

カラム名：
 Index(['糖度', '酸度'], dtype='object') 

値：
 [[10.   0.5]
 [12.   0.6]
 [ 8.   1. ]
 [ 9.   0.8]
 [10.   0.7]
 [15.   1. ]] 

絶対座標指定：
 0.5 

絶対座標指定：
       糖度
リンゴ1  10
リンゴ2  12
リンゴ3   8 

ラベル指定：
 リンゴ1    10
リンゴ2    12
リンゴ3     8
リンゴ4     9
リンゴ5    10
リンゴ6    15
Name: 糖度, dtype: int64 

ラベル指定：
 糖度    10.0
酸度     0.5
Name: リンゴ1, dtype: float64 



## DataFrame(Pandas)とndarray(Numpy)の関係

In [3]:
# Dataframeをndarrayに変換
array_p1=np.array(df_p1)
dfkyoka=df_p1.index
dfname=df_p1.columns
print("インデックス\n",dfkyoka,"\n")
print("カラム\n",dfname,"\n")
print("値\n",array_p1,"\n")

インデックス
 Index(['リンゴ1', 'リンゴ2', 'リンゴ3', 'リンゴ4', 'リンゴ5', 'リンゴ6'], dtype='object') 

カラム
 Index(['糖度', '酸度'], dtype='object') 

値
 [[10.   0.5]
 [12.   0.6]
 [ 8.   1. ]
 [ 9.   0.8]
 [10.   0.7]
 [15.   1. ]] 



In [4]:
# ndarrayをdataframeに変換
df_p2=pd.DataFrame(array_p1)
df_p2.index=dfkyoka
df_p2.columns=dfname
print(df_p2)

        糖度   酸度
リンゴ1  10.0  0.5
リンゴ2  12.0  0.6
リンゴ3   8.0  1.0
リンゴ4   9.0  0.8
リンゴ5  10.0  0.7
リンゴ6  15.0  1.0


In [5]:
print("dataframeサイズ：",df_p1.size)
print("arrayサイズ：",array_p1.size,"\n")
print("dataframeシェイプ",df_p1.shape)
print("arrayシェイプ：",array_p1.shape,"\n")
print("dataframe長さ",len(df_p1))
print("array長さ：",len(array_p1),"\n")
print("dataframe座標指定：",df_p1.iloc[3,1])
print("array座標指定：",array_p1[3,1])

dataframeサイズ： 12
arrayサイズ： 12 

dataframeシェイプ (6, 2)
arrayシェイプ： (6, 2) 

dataframe長さ 6
array長さ： 6 

dataframe座標指定： 0.8
array座標指定： 0.8


## DataFrame(Pandas)とndarray(Numpy)で行列演算

In [6]:
#行列の定義
df_x=pd.DataFrame({'c1':[1,4,7],'c2':[2,5,8],'c3':[3,6,9]})
array_x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("dataframe行列\n",df_x,"\n")
print("array行列\n",array_x,"\n")

dataframe行列
    c1  c2  c3
0   1   2   3
1   4   5   6
2   7   8   9 

array行列
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [7]:
print('最大値（行ごと）は\n', df_x.max(axis=1), "\n")
print('最大値（列ごと）は\n', df_x.max(axis=0), "\n")
print('最大値のインデックス（列ごと）:\n', df_x.idxmax(axis=0), "\n")
print('最小値（行ごと）は\n', df_x.min(axis=1), "\n")
print('平均値（行ごと）は\n', df_x.mean(axis=1), "\n")
print('分散（行ごと）は\n', df_x.var(axis=1), "\n")
print('標準偏差（行ごと）は\n', df_x.std(axis=1), "\n")
print('要素ごとのルートは\n', np.sqrt(df_x), "\n")
print('要素ごとのべき乗は\n', df_x ** 2, "\n")
print('要素ごとの掛け算は\n', df_x * df_x, "\n")
print('要素ごとの割り算は\n', df_x / df_x, "\n")
print('要素ごとの足し算は\n', df_x + df_x, "\n")
print('行列の掛け算は\n', df_x.dot(df_x.T), "\n")

最大値（行ごと）は
 0    3
1    6
2    9
dtype: int64 

最大値（列ごと）は
 c1    7
c2    8
c3    9
dtype: int64 

最大値のインデックス（列ごと）:
 c1    2
c2    2
c3    2
dtype: int64 

最小値（行ごと）は
 0    1
1    4
2    7
dtype: int64 

平均値（行ごと）は
 0    2.0
1    5.0
2    8.0
dtype: float64 

分散（行ごと）は
 0    1.0
1    1.0
2    1.0
dtype: float64 

標準偏差（行ごと）は
 0    1.0
1    1.0
2    1.0
dtype: float64 

要素ごとのルートは
          c1        c2        c3
0  1.000000  1.414214  1.732051
1  2.000000  2.236068  2.449490
2  2.645751  2.828427  3.000000 

要素ごとのべき乗は
    c1  c2  c3
0   1   4   9
1  16  25  36
2  49  64  81 

要素ごとの掛け算は
    c1  c2  c3
0   1   4   9
1  16  25  36
2  49  64  81 

要素ごとの割り算は
     c1   c2   c3
0  1.0  1.0  1.0
1  1.0  1.0  1.0
2  1.0  1.0  1.0 

要素ごとの足し算は
    c1  c2  c3
0   2   4   6
1   8  10  12
2  14  16  18 

行列の掛け算は
     0    1    2
0  14   32   50
1  32   77  122
2  50  122  194 



In [8]:
#arrayの各種演算
print('最大値（行ごと）は\n',np.max(array_x,axis=1),"\n")
print('最大値（列ごと）は\n',np.max(array_x,axis=0),"\n")
print('最大値のインデックス（列ごと）:\n', np.argmax(array_x,axis=0),"\n")
print('最小値（行ごと）は\n',np.min(array_x,axis=1),"\n")
print('平均値（行ごと）は\n',np.mean(array_x,axis=1),"\n")
print('分散（行ごと）は\n',np.var(array_x,axis=1,ddof=1),"\n")
print('標準偏差（行ごと）は\n',np.std(array_x,axis=1,ddof=1),"\n")
print('要素ごとのルートは\n',np.sqrt(array_x),"\n")
print('要素ごとのべき乗は\n',array_x**2,"\n")
print('要素ごとのべき乗は\n',np.power(array_x,2),"\n")
print('要素ごとの掛け算は\n',array_x*array_x,"\n")
print('要素ごとの割り算は\n',array_x/array_x,"\n")
print('要素ごとの足し算は\n',array_x+array_x,"\n")
print('行列の掛け算は\n',array_x.dot(array_x.T),"\n")

最大値（行ごと）は
 [3 6 9] 

最大値（列ごと）は
 [7 8 9] 

最大値のインデックス（列ごと）:
 [2 2 2] 

最小値（行ごと）は
 [1 4 7] 

平均値（行ごと）は
 [2. 5. 8.] 

分散（行ごと）は
 [1. 1. 1.] 

標準偏差（行ごと）は
 [1. 1. 1.] 

要素ごとのルートは
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]] 

要素ごとのべき乗は
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

要素ごとのべき乗は
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

要素ごとの掛け算は
 [[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

要素ごとの割り算は
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

要素ごとの足し算は
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]] 

行列の掛け算は
 [[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]] 

